version: '3.8'

services:

  #BBDDD
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: testing
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint.dat
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - dbnet
    ports:
      - "5432:5432"

  # GESTOR VISUAL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./backups:/backups
    networks:
      - dbnet

volumes:
  postgres_data:
  pgadmin_data:

networks:
  dbnet:
    driver: bridge
